# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    form.company.flow.register:
        class: BDBundle\Form\company\Flow\RegisterFlow
        parent: craue.form.flow

    bdbundle.upload_listener:
        class: BDBundle\EventListener\UploadListener
#       arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: kernel.event_listener, event: oneup_uploader.post_persist, method: onUpload }